### ISSUE TITLE
No logs when trying to deploy the MCP server on an OpenShift environment

### ISSUE THREAD

**Issue by hemajv** [manusa/kubernetes-mcp-server#32]
@manusa I'm trying to follow the `Dockerfile` to create a similar `Containerfile` for deploying this MCP server on my OpenShift environment. However, after successfully building my Containerfile and using it as an image in my OpenShift deployment, I don't see any logs in the pod running, so not sure if the MCP server is actually running correctly.

This is my `Containerfile`

```
FROM registry.access.redhat.com/ubi9/ubi:latest as builder

WORKDIR /app
USER root
RUN dnf install -y wget tar git make && \
    wget https://go.dev/dl/go1.24.1.linux-amd64.tar.gz && \
    tar -C /usr/local -xzf go1.24.1.linux-amd64.tar.gz && \
    rm -f go1.24.1.linux-amd64.tar.gz
ENV PATH="/usr/local/go/bin:${PATH}"
RUN git clone https://github.com/manusa/kubernetes-mcp-server.git && \
    cd kubernetes-mcp-server && \
    make build

FROM registry.access.redhat.com/ubi9/ubi-minimal:latest
WORKDIR /app
COPY --from=builder /app/kubernetes-mcp-server/kubernetes-mcp-server /app/kubernetes-mcp-server
ENTRYPOINT ["./kubernetes-mcp-server", "--sse-port", "8080"]

EXPOSE 8080
```

This is my OpenShift `deployment.yaml`:

```
kind: Deployment
apiVersion: apps/v1
metadata:
  name: ocp-mcp-server
  labels:
    app: ocp-mcp-server
spec:
  selector:
    matchLabels:
      app: ocp-mcp-server
  replicas: 1
  template:
    metadata:
      labels:
        app: ocp-mcp-server
        deployment: ocp-mcp-server
    spec:
      containers:
      - name: ocp-mcp-server
        image: quay.io/hveeradh/ocp-mcp-server:latest
        ports:
          - containerPort: 8080
            protocol: TCP
        command: ["./kubernetes-mcp-server"]
        args: ["--sse-port", "8080"]
        resources: {}
---
apiVersion: v1
kind: Service
metadata:
  name: ocp-mcp-server
  labels:
    app: ocp-mcp-server
spec:
  selector:
    app: ocp-mcp-server
    deployment: ocp-mcp-server
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
```

**Output**

A pod is running, but without any logs. When I ssh into the pod and run:
 
`./kubernetes-mcp-server --sse-port 8080` 

I get, `panic: listen tcp :8080: bind: address already in use`

**Expected Output**

 I should see some logs in the pod like:
```
INFO: Listening on port 8080
INFO: SSE endpoint: http://localhost:8080/sse
```
